name: 'Funny comments'
description: 'Adds a funny comment on each issue or PR'
author: 'Marta83'
inputs:
  GITHUB_TOKEN:
    description: 'Github Token for authentication'
    required: true
outputs:
  comment-url:
    description: 'The PR comment URL'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "yellow"
  icon: "bell"  
